block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
  "ci-linux (stable)",
  "ci-linux (1.40.0)",
  "rt-ci-linux (stable)",
  "rt-ci-linux (1.39.0)",
  "rt-ci-other-os (macOS-latest)",
  "rt-ci-other-os (windows-latest)",
  "rustfmt",
  "clippy",
]
