dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=thumbv6m-none-eabi
    - env: TARGET=thumbv7m-none-eabi
    - env: TARGET=thumbv7em-none-eabi
    - env: TARGET=thumbv7em-none-eabihf
env: TARGET=x86_64-unknown-linux-gnu

install:
  # NOTE(TRAVIS_BRANCH) Travis is configured to only build *pushes* (not PRs).
  - if [ $TRAVIS_BRANCH != master ] || [ $TRAVIS_EVENT_TYPE = cron ]; then
      curl https://sh.rustup.rs -sSf |
        sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION;

      source ~/.cargo/env;

      cargo install --git https://github.com/japaric/cross -f;
    fi

script:
  # NOTE(TRAVIS_BRANCH) See the NOTE in the `install` section
  - if [ $TRAVIS_BRANCH != master ] || [ $TRAVIS_EVENT_TYPE = cron ]; then
      sh ci/script.sh
    fi

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
