[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to Cortex-M processors"
documentation = "https://docs.rs/cortex-m"
keywords = ["arm", "cortex-m", "register", "peripheral"]
license = "MIT OR Apache-2.0"
name = "cortex-m"
readme = "README.md"
repository = "https://github.com/rust-embedded/cortex-m"
version = "0.5.10"

[dependencies]
aligned = "0.2.0"
bare-metal = "0.2.0"
volatile-register = "0.2.0"
cortex_m_0_6 = { package = "cortex-m", version = "0.6.0" }

[features]
cm7-r0p1 = ["cortex_m_0_6/cm7-r0p1"]
const-fn = ["bare-metal/const-fn", "cortex_m_0_6/const-fn"]
inline-asm = ["cortex_m_0_6/inline-asm"]
