[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Low level access to Cortex-M processors"
documentation = "https://docs.rs/cortex-m"
keywords = ["arm", "cortex-m", "register", "peripheral"]
license = "MIT OR Apache-2.0"
name = "cortex-m"
repository = "https://github.com/japaric/cortex-m"
version = "0.4.4"

[build-dependencies]
cc = "1.0.10"

[dependencies]
volatile-register = "0.2.0"

[dependencies.aligned]
default-features = false
version = "0.1.2"

[dependencies.bare-metal]
default-features = false
version = "0.1.2"

[features]
cm7-r0p1 = []
default = ["inline-asm"]
inline-asm = []
