[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
description = "Low level access to Cortex-M processors"
documentation = "https://docs.rs/cortex-m"
keywords = ["arm", "cortex-m", "register", "peripheral"]
license = "MIT OR Apache-2.0"
name = "cortex-m"
repository = "https://github.com/japaric/cortex-m"
version = "0.2.5"

[dependencies]
volatile-register = "0.2.0"

[dependencies.cortex-m-semihosting]
version = "0.1.3"