[package]
name = "xtask"
version = "0.0.0"
authors = ["The Cortex-M Team <cortex-m@teams.rust-embedded.org>"]
edition = "2018"
publish = false

[[test]]
name = "ci"
harness = false

[dependencies]
ar = "0.8.0"

[dependencies.object]
version = "0.21.1"
features = ["write"]
