language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv6m-none-eabi
      rust: stable
      sudo: true
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv6m-none-eabi CC=clang
      rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: stable
      sudo: true
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi CC=clang
      rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabi
      rust: stable
      sudo: true
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabi CC=clang
      rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabihf
      rust: stable
      sudo: true
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabihf CC=clang
      rust: stable
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
      sudo: true
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      sudo: true
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      sudo: true
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly
      sudo: true
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cache

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
