language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

    - env: TARGET=thumbv6m-none-eabi
      rust: stable
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

    - env: TARGET=thumbv6m-none-eabi CC=clang
      rust: stable

    - env: TARGET=thumbv7m-none-eabi
      rust: stable
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

    - env: TARGET=thumbv7m-none-eabi CC=clang
      rust: stable

    - env: TARGET=thumbv7em-none-eabi
      rust: stable
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

    - env: TARGET=thumbv7em-none-eabi CC=clang
      rust: stable

    - env: TARGET=thumbv7em-none-eabihf
      rust: stable
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

    - env: TARGET=thumbv7em-none-eabihf CC=clang
      rust: stable

    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cache

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
