[package]
name = "cortex-m-rt"
version = "0.1.0"
authors = ["Jorge Aparicio <japaricious@gmail.com>"]

[dependencies]
r0 = "0.2.1"

[dependencies.cortex-m]
optional = true
version = "0.2.2"

[dependencies.cortex-m-semihosting]
optional = true
version = "0.1.3"

[dependencies.compiler_builtins]
features = ["mem"]
git = "https://github.com/rust-lang-nursery/compiler-builtins"

[features]
default = ["exceptions"]
# handle exceptions using the default handler
exceptions = ["cortex-m"]
linker-script = []
panic-over-itm = ["cortex-m"]
panic-over-semihosting = ["cortex-m-semihosting"]