[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "no-std"]
description = "Minimal runtime / startup for Cortex-M microcontrollers"
documentation = "https://docs.rs/cortex-m-rt"
readme = "README.md"
keywords = ["arm", "cortex-m", "runtime", "startup"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rt"
repository = "https://github.com/japaric/cortex-m-rt"
version = "0.5.3"

[dependencies]
r0 = "0.2.1"
cortex-m-rt-macros = { path = "macros", version = "0.1.0" }

[dev-dependencies]
panic-semihosting = "0.3.0"
panic-abort = "0.2.0"
cortex-m = "0.5.4"

[features]
device = []
