[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
description = "Minimal runtime / startup for Cortex-M microcontrollers"
documentation = "https://docs.rs/cortex-m-rt"
keywords = ["arm", "cortex-m", "runtime", "startup"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rt"
repository = "https://github.com/japaric/cortex-m-rt"
version = "0.1.0"

[dependencies]
r0 = "0.2.1"

[dependencies.cortex-m]
optional = true
version = "0.2.3"

[dependencies.cortex-m-semihosting]
optional = true
version = "0.1.3"

[features]
default = ["exceptions", "linker-script"]
# handle exceptions using the default handler
exceptions = ["cortex-m"]
linker-script = []
panic-over-itm = ["cortex-m"]
panic-over-semihosting = ["cortex-m-semihosting"]