block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
  "ci-linux (stable, x86_64-unknown-linux-gnu)",
  "ci-linux (stable, thumbv6m-none-eabi)",
  "ci-linux (stable, thumbv7m-none-eabi)",
  "ci-linux (stable, thumbv7em-none-eabi)",
  "ci-linux (stable, thumbv7em-none-eabihf)",
  "ci-linux (stable, thumbv8m.main-none-eabi)",
  "ci-linux (1.39.0, x86_64-unknown-linux-gnu)",
  "ci-linux (1.39.0, thumbv6m-none-eabi)",
  "ci-linux (1.39.0, thumbv7m-none-eabi)",
  "ci-linux (1.39.0, thumbv7em-none-eabi)",
  "ci-linux (1.39.0, thumbv7em-none-eabihf)",
  "ci-linux (1.39.0, thumbv8m.main-none-eabi)",
  "Rustfmt"
]
